### ISSUE TITLE
nvcc problem? bare_metal version is not defined error?

### ISSUE THREAD

**Issue by kimnamwook1** [Yuanshi9815/Video-Infinity#12]
I use Anaconda prompt to install this program.  I also install cuda 12.5 version too. 

```
(video_infinity_vc2) D:\Development\Video-Infinity>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:36:51_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
```

But still when I enter "pip install -r requirements.txt" command, this error comes out. 

```
Using cached causal_conv1d-1.2.0.post2.tar.gz (7.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      C:\Users\79223\AppData\Local\Temp\pip-install-z5nw_b1t\causal-conv1d_9a4ebdf4e08b4f789917ba615aed14fb\setup.py:74: UserWarning: causal_conv1d was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\79223\AppData\Local\Temp\pip-install-z5nw_b1t\causal-conv1d_9a4ebdf4e08b4f789917ba615aed14fb\setup.py", line 108, in <module>
          if bare_metal_version >= Version("11.8"):
      NameError: name 'bare_metal_version' is not defined


      torch.__version__  = 2.3.1+cpu


      [end of output]
```

I found some solutions for nvcc and nccl problem, So i download nccl 2.21.5 and solve .tar file and add to 'system variable' 's path too but still problem doesnt solve. 

I use Window 11 environment. How can I solve this problem?

**Comment by Adamdad** [comment]
Dear @kimnamwook1,
Can you provide a full list of your packages in environment `video_infinity_vc2`.

I guess it is the nvcc cuda version is too high, such that some packages is not compatible with it. But I need to see the full package list to resolve this.

Best,

**Comment by kimnamwook1** [comment]
HI, I am not good developer so I don't know about full Package environment, Will you suggest me some examples? 


-----Original Message-----

**Comment by Adamdad** [comment]
Hello, This should be easy. Within your `video_infinity_vc2` env, do

```shell
conda list
```
 and copy all the package information and paste under this issue.

**Comment by kimnamwook1** [comment]
this is my list 


-----Original Message-----

**Comment by Adamdad** [comment]
@kimnamwook1 Sorry, but I see no list attached?

**Comment by kimnamwook1** [comment]
Sorry I Answer with E-mail! I will attatch list below

----
(video_infinity_vc2) D:\Development\Video-Infinity>conda list
# packages in environment at C:\Users\79223\anaconda3\envs\video_infinity_vc2:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h2bbff1b_6
ca-certificates           2024.7.2             haa95532_0
certifi                   2024.7.4                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
diffusers                 0.29.2                   pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
huggingface-hub           0.23.4                   pypi_0    pypi
idna                      3.7                      pypi_0    pypi
imageio                   2.34.2                   pypi_0    pypi
importlib-metadata        8.0.0                    pypi_0    pypi
intel-openmp              2021.4.0                 pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
libffi                    3.4.4                hd77b12b_1
markupsafe                2.1.5                    pypi_0    pypi
mkl                       2021.4.0                 pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
networkx                  3.3                      pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
openssl                   3.0.14               h827c3e9_0
packaging                 24.1                     pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.0            py310haa95532_0
python                    3.10.14              he1021f5_1
pyyaml                    6.0.1                    pypi_0    pypi
regex                     2024.5.15                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
safetensors               0.4.3                    pypi_0    pypi
setuptools                69.5.1          py310haa95532_0
sqlite                    3.45.3               h2bbff1b_0
sympy                     1.13.0                   pypi_0    pypi
tbb                       2021.13.0                pypi_0    pypi
tk                        8.6.14               h0416ee5_0
tokenizers                0.19.1                   pypi_0    pypi
torch                     2.3.1                    pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
transformers              4.42.4                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024a                h04d1e81_0
urllib3                   2.2.2                    pypi_0    pypi
vc                        14.2                 h2eaa2aa_4
vs2015_runtime            14.29.30133          h43f2093_4
wheel                     0.43.0          py310haa95532_0
xz                        5.4.6                h8cc25b3_1
zipp                      3.19.2                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_1

-----Original Message-----
